### ISSUE TITLE
Erro: flask run

### ISSUE THREAD

**Issue by wilyJ80** [G2BC/plasticome-backend#1]
> 6. Seja feliz e pode brincar com o plasticome!

**Como brincar com o plasticome?**

```
(plasticome-py3.10) root@123e20a40c93:/app# flask run
2024-03-25 18:51:51,387 - matplotlib.font_manager - INFO - generated new fontManager
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/plasticome-9TtSrW0h-py3.10/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/root/.cache/pypoetry/virtualenvs/plasticome-9TtSrW0h-py3.10/lib/python3.10/site-packages/flask/cli.py", line 1064, in main
    cli.main()
  File "/root/.cache/pypoetry/virtualenvs/plasticome-9TtSrW0h-py3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/plasticome-9TtSrW0h-py3.10/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.cache/pypoetry/virtualenvs/plasticome-9TtSrW0h-py3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.cache/pypoetry/virtualenvs/plasticome-9TtSrW0h-py3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/plasticome-9TtSrW0h-py3.10/lib/python3.10/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/plasticome-9TtSrW0h-py3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/plasticome-9TtSrW0h-py3.10/lib/python3.10/site-packages/flask/cli.py", line 912, in run_command
    raise e from None
  File "/root/.cache/pypoetry/virtualenvs/plasticome-9TtSrW0h-py3.10/lib/python3.10/site-packages/flask/cli.py", line 898, in run_command
    app = info.load_app()
  File "/root/.cache/pypoetry/virtualenvs/plasticome-9TtSrW0h-py3.10/lib/python3.10/site-packages/flask/cli.py", line 309, in load_app
    app = locate_app(import_name, name)
  File "/root/.cache/pypoetry/virtualenvs/plasticome-9TtSrW0h-py3.10/lib/python3.10/site-packages/flask/cli.py", line 219, in locate_app
    __import__(module_name)
  File "/app/plasticome/routes/app.py", line 6, in <module>
    from plasticome.controllers.pipeline_controller import execute_main_pipeline
  File "/app/plasticome/controllers/pipeline_controller.py", line 5, in <module>
    from plasticome.services.dbcan_result_filter_service import dbcan_result_filter
  File "/app/plasticome/services/dbcan_result_filter_service.py", line 42, in <module>
    cazy_info_set = get_cazy_info()
  File "/app/plasticome/services/dbcan_result_filter_service.py", line 20, in get_cazy_info
    enzymes_info, error = get_all_enzymes(
  File "/app/plasticome/services/plasticome_metadata_service.py", line 13, in get_all_enzymes
    token, error = authenticate_user(username, secret)
  File "/app/plasticome/services/auth_user_service.py", line 13, in authenticate_user
    response = requests.post(
  File "/root/.cache/pypoetry/virtualenvs/plasticome-9TtSrW0h-py3.10/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/plasticome-9TtSrW0h-py3.10/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/plasticome-9TtSrW0h-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/root/.cache/pypoetry/virtualenvs/plasticome-9TtSrW0h-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/root/.cache/pypoetry/virtualenvs/plasticome-9TtSrW0h-py3.10/lib/python3.10/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/root/.cache/pypoetry/virtualenvs/plasticome-9TtSrW0h-py3.10/lib/python3.10/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None/auth': No scheme supplied. Perhaps you meant https://None/auth?
(plasticome-py3.10) root@123e20a40c93:/app# 
```

**Comment by blueevee** [comment]
Não tinha visto essa mensagem, kkkkkkkkkkk, não sei se tu já conseguiu rodar, mas percebi que tinham alguns passos que estavam implícitos na minha cabeça, atualizei a lista lá.
Ahhh e outra coisa, como tu rodou no linux aparentemente, provavelmente alguns comandos podem ser diferentes, principalmente os comandos que executam as imagens docker, não tenho certeza que esse foi o problema, mas pode ser 1 dos, e também o .env sem as urls/infos que o projeto precisa pra rodar, a base pra consultar etc.
